build:
  image: zavalit/kafka-rest-server-builder
  commands: 
     - wget -qO- https://get.docker.com/ | sh
     - /bin/bash /srv/project/build
     - cd /kafka-rest-server-master && docker build -t zavalit/kafka-rest-server .

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PSW
    email: $$DOCKER_EMAIL
    repo: zavalit/kafka-rest-server
    when:
      repo: zavalit/kafka-rest-server
      branch: master
