build:
  image: zavalit/kafka-rest-server-builder
  pull: true
  commands: 
     - sbt assembly
     - docker build -t zavalit/kafka-rest-server .

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PSW
    email: $$DOCKER_EMAIL
    repo: zavalit/kafka-rest-server
    when:
      repo: zavalit/kafka-rest-server
      branch: master
